### ISSUE TITLE
Calendar issue

### ISSUE THREAD

**Issue by ConorOD** [CS3305X/project#3]
![image](https://cloud.githubusercontent.com/assets/7931260/6240520/ace3e6a2-b707-11e4-9ee8-78f9d573c96a.png)

There seems to be an issue when creating events in the calendar, the users ID is not added to the database?

**Comment by WillMurphy93** [comment]
Seems to be working now. Just make sure you are logged into the system before adding an event.

![image](https://cloud.githubusercontent.com/assets/9108130/6267285/8cf9927c-b83a-11e4-8f4d-293e7609f3d3.png)
